apiVersion: apps/v1
kind: Deployment
metadata:
    name: connfun-wechat-pay-deploy
    namespace: default
spec:
    selector:
        matchLabels:
            app: connfun-wechat-pay
            release: dev
    template:
        metadata:
            labels:
                app: connfun-wechat-pay
                release: dev
        spec:
            containers:
            - name: connfun-wechat-pay-containers
              image: connfun.com/wechat-pay:latest
              imagePullPolicy: Never
              ports:
              - name: http
                containerPort: 5000
              volumeMounts:
              - mountPath: /mnt/pem
                name: wechat-pem
              env:
              - name: APP_ID
                value: "<appid>"
              - name: MCH_ID
                value: "<mchid>"
              - name: SUB_APP_ID
                value: "<sub_appid>"
              - name: SUB_MCH_ID
                value: "<sub_mchid>"
              - name: SUB_KEY
                value: "<subkey>"
              - name: API_CERT
                value: "/mnt/pem/apiclient_cert.pem"
              - name: API_KEY
                value: "/mnt/pem/apiclient_key.pem"
            volumes:
            - name: wechat-pem
              hostPath:
                  path: /


